site_name: ZJU IOpt 2023 Fall
site_url: https://zhoutimemachine.github.io/2023_IOpt
repo_name: ZTM/2023_IOpt
repo_url: https://github.com/ZhouTimeMachine/2023_IOpt/
edit_uri: tree/master/docs
site_description: 浙江大学 2023 秋冬《优化基本理论与方法》(Introductory Lectures on Optimization) 课程网站
copyright: Copyright &copy; 2023 <a href="https://github.com/ZhouTimeMachine" target="_blank" rel="noopener">ZhouTimeMachine</a>

nav:
  - Home: index.md
  - Environment: latex.md
  - Math Formula: symbol.md
  - Coursework (1): hw1.md
  - Coursework (2): hw2.md
  - Coursework (3): hw3.md

theme:
  name: material
  language: zh
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: 夜间模式
    - media: "(prefers-color-scheme: dark)"
      primary: teal
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: 日间模式
  features:
    - content.code.copy
    - navigation.footer
    # - navigation.tabs
    # - navigation.sections
  icon:
    repo: fontawesome/brands/git-alt
    
plugins:
  - search
  - heti:
      extra_skipped_class:
        - arithmatex
      disable_serve: false

extra_javascript:
  - https://cdn.tonycrane.cc/utils/katex.min.js
  - js/katex.js

extra_css:
  - https://cdn.tonycrane.cc/utils/katex.min.css
  - https://fonts.googleapis.com/css?family=Roboto:500,500i,600,600i&display=fallback
  - css/custom.css
  # - css/style.css

markdown_extensions:
  - admonition # mkdocs 警告框
  - md_in_html # 脚注
  - meta # 自定义文章元数据
  - pymdownx.caret # 下划线
  - pymdownx.mark # 文本高亮
  - pymdownx.tilde # 删除线
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.arithmatex: # 数学公式的 TeX 语法支持
      generic: true
  - pymdownx.emoji: # 表情支持
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      linenums: true
  - pymdownx.tasklist: # 任务清单支持
      custom_checkbox: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - tables
  # - toc: # 大纲
  #     permalink: true
  #     slugify: !!python/name:pymdownx.slugs.uslugify